CC=gcc
CFLAGS=-g

test2a:
	./longestArg # no parameters
	./longestArg " only one parameter "
	./longestArg " biggest parameter " " at " " start "
	./longestArg " biggest " " parameter " " at " " end " " very very very big parameter "
	./longestArg " answer " " somewhere " " in " " the " " middle "
	./longestArg " two " " strings " " the " " same " " length " " ha ha !"


test2b:
	./c2f -c 50
	./c2f -f 1
	./c2f -c afa
	./c2f -f 214.asf
	./c2f
